####sudo docker run -d -p 50002:50002 -e EXTRAS="--login s1 --contestpassword contest" -v /home/control/pc2datadir:/pc2data --name mypc2 pc2server
#sudo docker-compose up -d
#sudo docker-compose down
version: "3.3"  # optional since v1.27.0
services:
  pc2server:
          container_name: myef
          image: pc2ef
          environment:
                  EXTRAS: "--login ef1"
                  XMX_VAR: "7G"
                  PC2IP_VAR: "172.20.16.10:50002"
                  ### used by pc2ws.properties
                  #ENABLESCOREBOARD_VAR: "yes"
                  #EVENTFEEDERPORT_VAR: "50443"
                  #ENABLETEAMS_VAR: "yes"
                  #ENABLESTARTTIME_VAR: "yes"
                  #ENABLELANGUAGES_VAR: "yes"
                  #ENABLEPROBLEMS_VAR: "yes"
                  #ENABLEFETCHRUN_VAR: "yes"

          ports:
                  - 50443:50443
          volumes:
                  - /home/control/pc2datadir_ef:/pc2data
