####sudo docker run -d -p 50002:50002 -e EXTRAS="--login s1 --contestpassword contest" -v /home/control/pc2datadir:/pc2data --name mypc2 pc2server
#sudo docker-compose up -d
#sudo docker-compose down
version: "3.3"  # optional since v1.27.0
services:
  pc2server:
          container_name: mypc2
          image: pc2server
          environment:
                  EXTRAS: "--login s1 --contestpassword contest"
                  XMX_VAR: "7G"
          ports:
                  - 50002:50002
          volumes:
                  - /home/control/pc2datadir:/pc2data
